# Site settings
title: PeP et al. e.V.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Physikstudierende und ehemalige Physikstudierende der TU Dortmund
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pep-dortmund.org" # the base hostname & protocol for your site
twitter_username: pepdortmund
twitter_url: https://twitter.com/pepdortmund
github_username: pep-dortmund
github_url: http://github.com/pep-dortmund/
facebook_url: https://www.facebook.com/groups/pep.dortmund/
xing_url: https://www.xing.com/communities/groups/pep-et-al-b621-1029339

# Build settings
markdown: kramdown
