# Site settings
title: PeP et al. e.V.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Physikstudierende und ehemalige Physikstudierende der TU Dortmund
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pep-dortmund.org" # the base hostname & protocol for your site
twitter_username: pepdortmund
github_username: pep-dortmund

# Build settings
markdown: kramdown
