# Site settings
plugins: [jekyll-paginate]
title: PeP et al. e.V.
email: kontakt@pep-dortmund.org
description: > # this means to ignore newlines until "baseurl:"
    Physikstudierende und ehemalige Physikstudierende der TU Dortmund
baseurl: '' # the subpath of your site, e.g. /blog
# the base hostname & protocol for your site
url: http://localhost:4000
twitter_username: pepdortmund
twitter_url: https://twitter.com/pepdortmund
github_username: pep-dortmund
github_url: http://github.com/pep-dortmund/
facebook_url: https://www.facebook.com/groups/pep.dortmund/
xing_url: https://www.xing.com/communities/groups/pep-et-al-b621-1029339
katex:
    path_to_js: "assets/js/katex.min.js"

# Build settings
markdown: kramdown
paginate: 6
paginate_path: "/archive/page:num/"
sass:
  style: compressed

collections: 
    - faq